### ISSUE TITLE
test `out` dir doesn't exist on new checkout of repo

### ISSUE THREAD

**Issue by juleskers** [eilslabs/igv-crawler#2]
After a fresh clone of the project, there is no `out` directory for `test-crawl.sh` to write to, causing the script to explode with an error.

I want the error to remain, because writing output to a non-existing dir is probably a configuration/user-error that we should alert to, instead of silently doing something unexpected.

figure out a way to get `git` to have this (empty) dir in the repo..

**Comment by vinjana** [comment]
Convention is to keep a ".keep" file in the otherwise empty directory.

**Comment by juleskers** [comment]
Thanks @vinjana for the fix; I've finally gotten around to applying it.
